vich_uploader:
    db_driver: orm

    mappings:
        collaborator_image:
            uri_prefix: /medias/images/collaborators
            upload_destination: '%kernel.project_dir%/public/medias/images/collaborators'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
